# -*- coding: utf-8 -*-
"""Numpy_index.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1INXFPNA8avpjuXn-yQczfE8pA8iEJ4tc
"""

#Slicing
import numpy as np
arr1 = np.array([[1,2,3],[5,6,7]])
arr2 = arr1[:, 1:3]
print(arr1)
print(arr2)

#Mutable
import numpy as np
arr1 = np.array([[1,2,3],[5,6,7]])
print('arr1 \n', arr1)
arr2 = arr1[:, 1:3]
print('arr2 \n', arr2)

print('Truoc khi thay doi \n', arr1[0, 1])
arr2[0, 0] = 99
print('Sau khi thay doi \n', arr1[0, 1])

#Get a row
import numpy as np
arr = np.array([[1,2,3],
                 [5,6,7],
                 [9,10,11]])
row_1 = arr[1, :]
row_2 = arr[1:2, :]
print(row_1, row_1.shape)
print(row_1, row_2.shape)

#Get a column
import numpy as np
arr = np.array([[1,2,3],
                 [5,6,7],
                 [9,10,11]])
col_1 = arr[:, 1]
col_2 = arr[:, 1:2]
print(col_1, col_1.shape)
print(col_2, col_2.shape)

#List as Indices
import numpy as np
arr = np.array([[1,2],
                 [3,4],
                 [5,6]])
out1 = arr[[0,1,2],[0,1,0]]
print('out1:\n', out1)
out2 = arr[[0,2],[1,1]]
print('out2:\n', out2)

#Boolean Indices
import numpy as np
arr = np.array([[1,2],
                 [3,4],
                 [5,6]])
print(arr)
bool_ind = (arr > 2)
print(bool_ind)