# -*- coding: utf-8 -*-
"""Numpy_introduce.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ommaJVt4gfJjYGXkNp23bpxREeXefKO2
"""

#Ex1:
import numpy as np
l = list(range(1, 4))
data = np.array(l)
print(data)
print(data[0])
print(data[1])

#Ex2
import numpy as np
l_1D = [1,2,3]
data = np.array(l_1D)
print(data)
print(data.shape)

#Ex3
import numpy as np
l_2D = [[1,2],[3,4],[5,6]]
data = np.array(l_2D)
print(data)
print(data.shape)

#Ex4
import numpy as np
l_3D = [
          [[1,2],[3,4],[5,6]],
          [[2,3],[4,5],[6,7]],
          [[3,4],[5,6],[7,8]]
        ]
data = np.array(l_3D)
print(data)
print(data.shape)

#Ex5
import numpy as np
data1 = np.array([1,2,3])
print(data1.dtype)
data2 = np.array([1.,2.,3.])
print(data2.dtype)
data3 = np.array([1,2,3], dtype = np.int32)
print(data3.dtype)